### ISSUE TITLE
Auto-complete list colours

### ISSUE THREAD

**Issue by NorthNick** [divanvisagie/nord-native#3]
With the VS Code 1.57.0 update, the default item on the auto-complete list has some of its characters coloured black on a grey background, making the item hard to read - see the attached screenshot.  Maybe some new colour setting has been added, which needs to be set appropriately.

![image](https://user-images.githubusercontent.com/1299353/121949320-3b3f1600-cd50-11eb-812e-c3318031ac12.png)

**Comment by divanvisagie** [comment]
Hi @NorthNick , thanks for the bug report.

It does seem that the [latest VSCode update](https://code.visualstudio.com/updates/v1_57#_updated-quick-pick-suggest-widget-colors) has added some new colours. I am working on an update that I will try and get out shortly. If this is really bothering you and time is of the essence, it is possible to override these colours in your settings.json

**Comment by divanvisagie** [comment]
@NorthNick I have released v0.0.7 with a fix. It works in JavaScript but I'de like to get confirmation from you that its resolved for PHP before closing off here.

**Comment by NorthNick** [comment]
Looks great in PHP. Many thanks for sorting it so quickly.
![image](https://user-images.githubusercontent.com/1299353/122956236-b9b33d80-d378-11eb-9b71-65a8a798941a.png)
